CREATE DATABASE bimbel_online;
USE bimbel_online;

CREATE TABLE tb_admin(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR(100) NOT NULL,
namaadmin VARCHAR(100) NOT NULL,
jenis_kelamin ENUM ('','L','P') DEFAULT '',
katasandi VARCHAR(40) NOT NULL,
UNIQUE(email)
)ENGINE=INNODB;

CREATE TABLE tb_pengajar(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR(100) NOT NULL,
username VARCHAR(100) NOT NULL,
namapengajar VARCHAR(100) NOT NULL,
jenis_kelamin ENUM ('','L','P') DEFAULT '',
katasandi VARCHAR(40) NOT NULL,
UNIQUE(email)
)ENGINE=INNODB;

CREATE TABLE tb_siswa(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR(100) NOT NULL,
username VARCHAR(100) NOT NULL,
namapeserta VARCHAR(100) NOT NULL,
jenis_kelamin ENUM ('','L','P') DEFAULT '',
katasandi VARCHAR(40) NOT NULL,
UNIQUE(email)
)ENGINE=INNODB;

CREATE TABLE tb_paket(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
namapaket VARCHAR(50)NOT NULL,
deskripsi TEXT
)ENGINE=INNODB;

CREATE TABLE tb_pembayaran(
id INT UNSIGNED,
namapeserta INT UNSIGNED,
namaadmin INT UNSIGNED,
namapembayaran VARCHAR (50)NOT NULL,
tanggal DATE,
bataspembayaran DATETIME,
jumlah DECIMAL (10,2),

FOREIGN KEY (namapeserta) REFERENCES tb_siswa(id) ON UPDATE CASCADE,
FOREIGN KEY (namaadmin) REFERENCES tb_admin(id) ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE tb_absensi(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
user_id INT UNSIGNED NOT NULL,
STATUS ENUM ('Hadir', 'Izin', 'Alfa') DEFAULT 'Hadir',
keterangan VARCHAR(255) DEFAULT NULL,
FOREIGN KEY (user_id) REFERENCES tb_siswa(id)
)ENGINE=INNODB;

CREATE TABLE tb_materi(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
judulmateri VARCHAR(100),
tipemateri VARCHAR(100),
namapengajar INT UNSIGNED,
deskripsi TEXT,

FOREIGN KEY (namapengajar) REFERENCES tb_pengajar(id) ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE tb_kelas(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
namakelas VARCHAR(50),
kodekelas VARCHAR(10),
judulmateri INT UNSIGNED,
tahunajaran YEAR,
catatanpertemuan TEXT,

FOREIGN KEY (judulmateri) REFERENCES tb_materi(id)ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE tb_detail_kelas(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
namapeserta INT UNSIGNED,
namakelas INT UNSIGNED,
namapengajar INT UNSIGNED,
jumlahpeserta INT,
jadwal VARCHAR(20),

FOREIGN KEY (namapeserta) REFERENCES tb_siswa(id)ON UPDATE CASCADE,
FOREIGN KEY (namakelas) REFERENCES tb_kelas(id)ON UPDATE CASCADE,
FOREIGN KEY (namapengajar) REFERENCES tb_pengajar(id)ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE tb_nilai(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
namapeserta INT UNSIGNED,
nilai_to INT NOT NULL,
nilai_tps INT NOT NULL,
nilai_tka INT NOT NULL,
nilai_total INT NOT NULL,

FOREIGN KEY (namapeserta) REFERENCES tb_siswa(id)ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE tb_detail_paket(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
namapaket INT UNSIGNED,
durasibelajar VARCHAR (25) NOT NULL,
jumlahsesi INT NOT NULL,
harga INT NOT NULL,
fitur VARCHAR(250) NOT NULL,

FOREIGN KEY (namapaket) REFERENCES tb_paket(id)ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE tb_jadwal(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
hari VARCHAR(10)NOT NULL,
tanggal DATE NOT NULL,
jam TIME NOT NULL,
sesi VARCHAR(50)NOT NULL,
judulmateri INT UNSIGNED,

FOREIGN KEY (judulmateri) REFERENCES tb_materi(id)ON UPDATE CASCADE
)ENGINE=INNODB;