CREATE DATABASE bimbel_online;
USE bimbel_online;

CREATE TABLE tb_admin(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR(100) NOT NULL,
namaadmin VARCHAR(100) NOT NULL,
katasandi VARCHAR(40) NOT NULL,
UNIQUE(email)
)ENGINE=INNODB;

CREATE TABLE tb_pengajar(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR(100) NOT NULL,
username VARCHAR(100) NOT NULL,
namapengajar VARCHAR(100) NOT NULL,
jenis_kelamin ENUM ('','L','P') DEFAULT '',
katasandi VARCHAR(40) NOT NULL,
UNIQUE(email)
)ENGINE=INNODB;

CREATE TABLE tb_siswa(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR(100) NOT NULL,
username VARCHAR(100) NOT NULL,
namasiswa VARCHAR(100) NOT NULL,
jenis_kelamin ENUM ('','L','P') DEFAULT '',
katasandi VARCHAR(40) NOT NULL,
UNIQUE(email)
)ENGINE=INNODB;


CREATE TABLE tb_absensi(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
user_id INT UNSIGNED NOT NULL,
STATUS ENUM ('Hadir', 'Izin', 'Alfa') DEFAULT 'Hadir',
keterangan VARCHAR(255) DEFAULT NULL,
FOREIGN KEY (user_id) REFERENCES tb_siswa(id)
)ENGINE=INNODB;

CREATE TABLE tb_materi(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
judulmateri VARCHAR(100),
tipemateri VARCHAR(100),
namapengajar INT UNSIGNED,
deskripsi TEXT,

FOREIGN KEY (namapengajar) REFERENCES tb_pengajar(id) ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE tb_kelas(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
namakelas VARCHAR(50),
kodekelas VARCHAR(10),
tahunajaran YEAR,
catatanpertemuan TEXT
)ENGINE=INNODB;


CREATE TABLE tb_nilai(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
namasiswa INT UNSIGNED,
nilai_to INT NOT NULL,
nilai_tps INT NOT NULL,
nilai_tka INT NOT NULL,
nilai_total INT NOT NULL,

FOREIGN KEY (namasiswa) REFERENCES tb_siswa(id)ON UPDATE CASCADE
)ENGINE=INNODB;


CREATE TABLE tb_jadwal(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
hari VARCHAR(10)NOT NULL,
tanggal DATE NOT NULL,
jam TIME NOT NULL,
sesi VARCHAR(50)NOT NULL,
judulmateri INT UNSIGNED,

FOREIGN KEY (judulmateri) REFERENCES tb_materi(id)ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE tb_daftar_siswa(
 id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
 namasiswa INT UNSIGNED,
 namakelas INT UNSIGNED,
    
 FOREIGN KEY (namasiswa) REFERENCES tb_siswa(id) ON UPDATE CASCADE,
 FOREIGN KEY (namakelas) REFERENCES tb_kelas(id) ON UPDATE CASCADE
)ENGINE=INNODB;
